pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:wei-janchang/mph_dissertation.git
          - cd mph_dissertation.git
          - git push --mirror git@bitbucket.org:wei-janchang/mph_dissertation.git